In [1]:
import numpy as np 

In [3]:
array_np = np.array([1,2,3,4])

In [4]:
type(array_np)

numpy.ndarray

In [5]:
tupla = np.array((1,2,3,4))

In [7]:
type(tupla)

numpy.ndarray

In [8]:
np.zeros((1))

array([0.])

In [9]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.zeros(([5,2]))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.zeros((5,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [19]:
np.ones((3,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
np.empty((3,3))

array([[6.90808839e-310, 0.00000000e+000, 6.90804040e-310],
       [2.69165541e-316, 6.90804040e-310, 6.90804040e-310],
       [0.00000000e+000, 6.90804040e-310, 3.95252517e-322]])

In [22]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [30]:
arreglo_pares = np.arange(0,20,2)

In [31]:
arreglo_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
arreglo_pares.size

10

In [33]:
arreglo_pares.shape

(10,)

In [34]:
arreglo_pares.ndim

1

In [35]:
arreglo_pares.reshape((5,2))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [36]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [39]:
np.arange(100000).reshape((10000,10))

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [40]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [41]:
a


array([10, 10, 10])

In [42]:
b

array([5, 5, 5])

In [43]:
# suma 
print(a + b )
 

[15 15 15]


In [44]:
# resta 
print(a-b)

[5 5 5]


In [45]:
#mult
print(a*b)

[50 50 50]


In [46]:
#div
print(a/b)

[2. 2. 2.]


In [47]:
#mod 
print(a%b)

[0 0 0]


In [48]:
a/2

array([5., 5., 5.])

In [49]:
arreglo_doce = np.arange(12)

In [51]:
arreglo_doce>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [53]:
arreglo_doce[arreglo_doce>5]

array([ 6,  7,  8,  9, 10, 11])

In [54]:
A = np.arange(4).reshape((2,2))

In [56]:
B = np.arange(4,8).reshape((2,2))

In [58]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [59]:
C = np.zeros_like(A)
np.dot(A,B,C)

array([[ 6,  7],
       [26, 31]])

In [60]:
C

array([[ 6,  7],
       [26, 31]])

In [64]:
arreglo_tres = np.arange(3)

In [65]:
arreglo_tres+=2

In [66]:
arreglo_tres

array([2, 3, 4])

In [67]:
arreglo_tres.sum()

9

In [68]:
arreglo_tres.max()

4

In [74]:
array_tres_cuatro = np.arange(24).reshape(6,2,2)

In [75]:
array_tres_cuatro

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [76]:
array_tres_cuatro.sum(axis=0)

array([[60, 66],
       [72, 78]])

In [77]:
array_tres_cuatro.sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28],
       [34, 36],
       [42, 44]])

In [79]:
array_tres_cuatro.sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37],
       [41, 45]])