In [1]:
import numpy as np

In [2]:
angulos_cero_noventa = np.array((0,30,45,60,90))

In [3]:
np.pi 

3.141592653589793

In [4]:
angulos_radianes = angulos_cero_noventa*np.pi / 180

In [5]:
angulos_radianes


array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [6]:
np.sin(angulos_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [7]:
np.tan(angulos_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [8]:
arreglos_random_diez = np.random.rand(10)

In [11]:
arreglos_random_diez = arreglos_random_diez*10

In [12]:
arreglos_random_diez

array([7.36243642, 6.66867137, 2.10211189, 7.01118156, 0.72129437,
       1.74328192, 2.75721036, 4.49142219, 6.66013455, 0.39812278])

In [13]:
arreglos_random_diez // 1

array([7., 6., 2., 7., 0., 1., 2., 4., 6., 0.])

In [14]:
arreglo_random_diez = np.random.randint(-10,100,10)

In [15]:
arreglo_random_diez

array([23, 86, 11, 53, 98, 17, -5, 76, 11, 35])

In [16]:
#media
arreglo_random_diez.mean()

40.5

In [17]:
# mediana
np.median(arreglos_random_diez)

3.6243162755190768

In [18]:
# standard deviation 
arreglos_random_diez.std() 

2.622495294821154

In [19]:
# variance 
arreglo_random_diez.var() 

1149.25