In [0]:
import numpy as np 

# Deber 
1. Crear con numpy array de shape (3,5) de ceros, (2,4) de unos, una matriz identidad de (4,4).
Luego imprimir para cada uno: el shape y el número de dimensiones: 

In [66]:
array_ceros = np.zeros((3,5))
array_unos = np.ones((2,4))
array_identidad = np.eye(4)
print(f"Array de ceros : \n {array_ceros}")
print(f"Array de unos: \n{array_unos}")
print(f"Array identidad \n {array_identidad} ")

Array de ceros : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array de unos: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array identidad 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 


In [67]:
print(f"shape del array de ceros {array_ceros.shape} y su numero de dimensiones {array_ceros.ndim}")
print(f"shape del array de unos {array_unos.shape} y su numero de dimensiones {array_unos.ndim}")
print(f"shape del array de identidad {array_identidad.shape} y su numero de dimensiones {array_identidad.ndim}")


shape del array de ceros (3, 5) y su numero de dimensiones 2
shape del array de unos (2, 4) y su numero de dimensiones 2
shape del array de identidad (4, 4) y su numero de dimensiones 2


2. Crear un array randomico de enteros de shape(5x3) que representa las notas de 5 estudiantes en 3 materias 
realizar 
* el promedio de notas por estudiante y materia
* la desviación estandar por estudiante y materia 
* la nota mínima por estudiante y materia 
* la nota máxima por estudiante y materia 

In [68]:
notas = np.random.randint(low=1,high=11,size=(5,3))
print(notas)

[[ 8  9  8]
 [ 2  6  2]
 [ 7  6  3]
 [ 5  4 10]
 [ 4  1 10]]


In [69]:
print(f"promedio por estudiante {notas.mean(axis=1)}")
print(f"promedio por materia {notas.mean(axis=0)}")

promedio por estudiante [8.33333333 3.33333333 5.33333333 6.33333333 5.        ]
promedio por materia [5.2 5.2 6.6]


In [70]:
print(f"std por estudiante {notas.std(axis=1)}")
print(f"std por materia {notas.std(axis=0)}")

std por estudiante [0.47140452 1.88561808 1.69967317 2.62466929 3.74165739]
std por materia [2.13541565 2.63818119 3.44093011]


In [71]:
print(f"nota minima por estudiante {notas.min(axis=1)}")
print(f"nota minima por materia {notas.min(axis=0)}")

nota minima por estudiante [8 2 3 4 1]
nota minima por materia [2 1 2]


In [72]:
print(f"nota maxima por estudiante {notas.max(axis=1)}")
print(f"nota maxima por materia {notas.max(axis=0)}")

nota maxima por estudiante [ 9  6  7 10 10]
nota maxima por materia [ 8  9 10]


3.En AI una neurona está definida por la siguiente expresion matematica: dot(x,w)+ b donde X es la matriz de  shape  (N,M) que representan las las n entradas con m atributos de un conjunto de datos, w son los pesos (weights)  b es bias (sesgo). implementar la expresion anterior utilizando numpy. 
w es un array de shape = M  y b es una array de shape=N cuyos elementos es un valor fijo.
* crear los arrays de manera randomica 
* cual es el resultado de la operacion 
* cual es el shape del resutado 

In [0]:
x = np.random.randint(100,size=(10,4))
w = np.random.rand(4)
b = np.ones(10)*5 
y_hat = np.dot(x,w) + b 

In [74]:
print(y_hat)

[33.32344305 30.76468857 16.19556449 24.37024687 64.43241641 90.43212985
 69.39509495 69.67467574 70.67219527 56.48312905]


In [75]:
print(f"resultado neurona shape: {y_hat.shape}")

resultado neurona shape: (10,)



4. Dado utilice numpy para evaluar un conjunto de elementos con la funcion 
f(x) = x*x + x*sin(x) + tan(x)
muestre el resultado 


In [0]:
def f(x):
  return x**2 +x*np.sin(x) + np.tan(x)

In [77]:
array = np.array([3,34,45])
print(f"resultado: {f(array)}")

resultado: [   9.28081348 1173.36531237 2064.91043379]


5. Dado el siguiente array encontrar: 
* las dos primeras filas 
* las dos primeras columnas 
* el primer y penultimo elemento 


In [0]:
array_5 = np.array([
    ["Alex","Segundo","No se que poner"],
    ["Que se yo","Alex","Gato"],
    ["Vamos", "Python", "is the best"]
])

In [80]:
print(f"dos primeras filas {array_5[:2,:]}")

dos primeras filas [['Alex' 'Segundo' 'No se que poner']
 ['Que se yo' 'Alex' 'Gato']]


In [81]:
print(f"dos primeras columnas {array_5[:,:2]}")

dos primeras columnas [['Alex' 'Segundo']
 ['Que se yo' 'Alex']
 ['Vamos' 'Python']]


In [82]:
filas = np.array([
    [0,2]
])
columnas =  np.array([
    [0,1]
])

print(f"primer y penultimo elemento del array {array_5[filas,columnas]}")

primer y penultimo elemento del array [['Alex' 'Python']]
